### ISSUE TITLE
Keep notes with checkbox content are omited from the output json file

### ISSUE THREAD

**Issue by DevinStetler** [valdineifer/keep-to-simplenote#1]
checkbox "listContent" content is lost during conversion.

**Comment by DevinStetler** [comment]
Add this code to ConvertJson.js to handle checkbox content:

`let listContent = ""`

`
if (Array.isArray(originalJson.listContent) && originalJson.listContent.length !== 0) {
       originalJson.listContent.forEach(li => {
            listContent += "\r\n- [" +
                ((li.isChecked == true) ? "x" : " ")
                    + "] " + li.text;
        })
}
`

then change the return statement to:
`
return {
        id: originalJson.id,
        content: originalJson.title + ((originalJson.textContent != undefined) ? '\r\n\r\n' + originalJson.textContent : "") + listContent,
        // creation date not available, use modified time for both
        creationDate: new Date(parseInt(originalJson.userEditedTimestampUsec) / 1000),
        lastModified: new Date(parseInt(originalJson.userEditedTimestampUsec) / 1000),
        tags,
    }
`

Note the date was not properly set in original code, so this sets the date properly also.

**Comment by valdineifer** [comment]
Thank you!
I had put this task in the TODO list, but I never came back to resolve it.
